version: "3.8"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566" # Main LocalStack API
      - "4571:4571" # S3
    environment:
      - SERVICES=s3,sqs
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./localstack:/tmp/localstack"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_started
    environment:
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=todo_db
      - DB_SSLMODE=disable
      - S3_ENDPOINT=http://localstack:4566
      - S3_REGION=us-east-1
      - S3_ACCESS_KEY_ID=test
      - S3_SECRET_ACCESS_KEY=test
      - S3_BUCKET=uploads
      - SQS_ENDPOINT=http://localstack:4566
      - SQS_REGION=us-east-1
      - SQS_QUEUE_URL=http://localstack:4566/000000000000/todo-queue

volumes:
  postgres_data:
